#!/bin/bash
# Begin service netfs
#
# Description : Network Filesystems Script
#
# Author      : DJ Lucas - dj@lucasit.com
#
# Version     : LFS/BLFS
#
# Notes       : Unmounts network filesystems
#
########################################################################

. /lib/lsb/init-functions

case "${1}" in
   stop)
      log_info_msg "Unmounting network volumes..."

      # The following line obtains a list from the output of
      # mount for all netfs types and anything that was
      # mounted with the _netdev option.
      NETMOUNTS=$(mount \
         | grep '_netdev\|smbfs\|ncpfs\|coda\|nfs\|cifs' \
         | cut -d " " -f 3 | sed ':a;$!N;s/\n/ /;ta')

      # Check to see if anything was listed from above
      # (see if anything actually needs to be unmounted)
      if [ -n "${NETMOUNTS}" ]; then
         # There is something mounted

         # Try and stop processes the nice way
         # (probably won't work in most cases)
         fuser -SIGTERM -km ${NETMOUNTS} > /dev/null 2>&1

         # Check and see if it found anything.  If it
         # did, then give 3 seconds for things to exit
         # the nice way before killing them off.
         # This one will work all of the time!
         if [ "${?}" = "0" ]; then
            sleep "${KILLDELAY:-3}"  # Default is 3, not minus 3
            fuser -km ${NETMOUNTS} > /dev/null 2>&1
         fi

         # We now need to unmount all network filesystems.
         # We will do this with two umount commands to allow
         # for broken behavior of smbmount, and also to make
         # certain that netmounts without the _netdev option
         # will still get unmounted.
         umount -af -O _netdev

         # Save the return value
         NERRVAL="${?}"

         # Now catch the rest of the network filesystems
         # by fstype.  This list can be extended later as
         # more network filesystems are supported by mount.
         umount -af -t coda,ncpfs,nfs,smbfs,nfsd,cifs

         if [ "${?}" = "0" ] && [ "${NERRVAL}" = "0" ]; then
           (exit 0)
         else
           (exit 1)
         fi

         evaluate_retval

      else
         # There is nothing mounted
         log_success_msg2 "No network volumes mounted!"
      fi
      ;;

   *)
      echo "Usage: ${0} {stop}"
      exit 1
      ;;
esac

exit 0

# End service netfs
